### ISSUE TITLE
I have one error.

### ISSUE THREAD

**Issue by peternara** [MarkAny-Vision-AI/CenterNeXt#15]
Thanks for publishing good code.

I have one error.

```
File "./python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "./python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "CenterNeXt/utils/data/dataset.py", line 106, in __getitem__
    foreground[bboxes_icy, bboxes_icx] = 1
IndexError: index 64 is out of bounds for axis 1 with size 64

```

I configure custom datasets, convert them to MSCOCO format, and while training, the following error exists.

I can't understand.
I applied this same data to yolox, but it works fine here.

Do you know about this problem?
@developer0hye

**Comment by developer0hye** [comment]
Hi @peternara 
We updated the code.
Check it again with the latest version!

**Comment by peternara** [comment]
@developer0hye 

Thanks for the quick reply. :) 
I will try it.

**Comment by peternara** [comment]
@developer0hye 
A similar error occurred elsewhere.
```
CenterNeXt/utils/data/dataset.py", line 146, in __getitem__
    classes_gaussian_heatmap[bbox_class] = transforms.scatter_gaussian_kernel(classes_gaussian_heatmap[bbox_class], bbox_icx, bbox_icy, bbox_w.item(), bbox_h.item())
  File "CenterNeXt/utils/data/transforms.py", line 424, in scatter_gaussian_kernel
    gaussian_kernel[bbox_icy, bbox_icx] = 1.
IndexError: index 64 is out of bounds for axis 1 with size 64

```

**Comment by developer0hye** [comment]
@peternara 
Thanks for reporting bug of our project!

We updated the code.
Check it again with the latest version!

**Comment by peternara** [comment]
@developer0hye 

thanks. 
It's working fine.. :)

**Comment by developer0hye** [comment]
@peternara 
I am a little bit worried about your case.

We didn't implement code for training a custom dataset, so I think mAP would not  be computed properly without some modification.

**Comment by peternara** [comment]
@developer0hye 

I'm going through some modifications to fit my dataset.
If anything goes wrong, I'll report the error.

**Comment by developer0hye** [comment]
@peternara 
Thanks!
